[Feat] Ellipsis 버튼 팝업 뷰 UI구현(구조변경)
Nexters/Fancy-Mouse-iOS pull request #26
Opened 2022-02-18 17:23 UTC by Hansangjin98

이전 #23 PR 에서 받은 리뷰 반영하여
외부에서 버튼 title, image, action 주입받아 StackView에 쌓는 식으로 구조 변경 완료했습니다!

2022-02-18 17:33 UTC, yeonduing reviewed
리뷰 반영 고마워🧡

2022-02-18 17:33 UTC, yeonduing commented on FancyMouse/Presentation/Voca/View/PopUpView/EllipsisView/EllipsisView.swift
> +    func addComponent(title: String, imageName: String, action: UIAction) {
애초에 이미지를 안받고 String으로 받은 이유가 있을까?

2022-02-18 19:10 UTC, iyovory commented on FancyMouse/Presentation/Voca/View/PopUpView/EllipsisView/EllipsisView.swift
> +    func addComponent(title: String, imageName: String, action: UIAction) {
이미지로 받게 되면 외부에서 UIImage를 생성해서 주입해줘야 하는데,
그렇게 되면 외부 코드가 길어지게 돼서 그냥 내부에서 이미지를 생성하게 해봤어!
버튼을 여러개 생성하게 될 수록 외부에서 UIImage를 생성하는데 사용되는 코드도 많아지다 보니까 깔끔하지 않은 것 같더라구

2022-02-18 19:15 UTC, Hansangjin98 commented on FancyMouse/Presentation/Voca/View/PopUpView/EllipsisView/EllipsisView.swift
> +    func addComponent(title: String, imageName: String, action: UIAction) {
이미지로 받게 되면 외부에서 UIImage를 생성해서 주입해줘야 하는데,
버튼이 여러 개 생성될수록 외부에서 이미지를 생성하는데 필요한 코드도 많아지게 되다 보니까 깔끔하지 않은 것 같더라구!

2022-02-19 05:05 UTC, yeonduing approved these changes

2022-02-19 17:11 UTC, yeonduing requested changes

2022-02-19 17:11 UTC, yeonduing commented on FancyMouse/Presentation/Voca/View/PopUpView/EllipsisView/EllipsisView.swift
> +        }()
컴퓨티드가 펑션 안에 있었네...? 이거 확인좀ㅎㅎㅎ

2022-02-20 14:22 UTC, lsh424 approved these changes

2022-02-20 18:18 UTC, Hansangjin98 commented on FancyMouse/Presentation/Voca/View/PopUpView/EllipsisView/EllipsisView.swift
> +        }()
반영 했습니다!! 승언님 감사합니다 😁
```ruby
    func addComponent(title: String, imageName: String, action: UIAction) {
        let button = UIButton()
        let image = UIImage(named: imageName)
        button.setTitle(title, for: .normal)
        button.setTitleColor(.white, for: .normal)
        button.titleLabel?.font = .spoqaMedium(size: 14)
        button.setImage(image, for: .normal)
        button.semanticContentAttribute = .forceLeftToRight
        button.addAction(action, for: .touchUpInside)
        
        stackView.addArrangedSubview(button)
    }
```

2022-02-22 00:41 UTC, yeonduing approved these changes

2022-02-22 14:34 UTC, merged