[Feat] 폴더 추가하기, 수정하기 기능 구현
Nexters/Fancy-Mouse-iOS pull request #67
Opened 2022-03-28 06:43 UTC by Hansangjin98

작업 내역
- 폴더 추가하기 기능 구현
- 폴더 수정하기 기능 구현

TODO
- Firebase에 데이터 송신 후 CollectionView reloadData 하는 부분에 이슈가 있음😭
- 단어장 탭 전체적으로 레이아웃 수정 필요

2022-03-28 13:19 UTC, yeonduing requested changes

2022-03-28 13:19 UTC, yeonduing commented on FancyMouse/Domain/UseCases/FolderUseCase.swift
> +        }
어떤 의미를 가졌는지 함수로 빼면 어떨까

2022-03-28 13:19 UTC, yeonduing commented on FancyMouse/Domain/UseCases/FolderUseCase.swift
>          }
어떤 의미를 가졌는지 함수로 빼면 어떨까

2022-03-28 13:19 UTC, yeonduing commented on FancyMouse/Presentation/Folder/View/FolderViewController.swift
>      private lazy var viewModel = FolderViewModel(useCase: FolderUseCase())
뷰모델을 주입받지 않네

2022-03-28 13:19 UTC, yeonduing commented on FancyMouse/Presentation/Folder/View/FolderViewController.swift
>                  guard let self = self else { return }
self 강한 캡쳐한 이유가 있을까?

2022-03-28 13:19 UTC, yeonduing commented on FancyMouse/Presentation/Folder/View/FolderViewController.swift
> +    func moreButtonEditWasTapped(_ folder: Folder) {
네이밍 같이 고민해보면 좋겠다

2022-03-28 13:19 UTC, yeonduing commented on FancyMouse/Presentation/Folder/View/FolderViewController.swift
> +        guard let colorName = folder.folderColor?.name else { return }
점을 줄여봅시바

2022-03-28 13:19 UTC, yeonduing commented on FancyMouse/Presentation/Folder/View/FolderViewController.swift
> +       folderAddEditView.viewModel.folderID.accept(folder.folderID)
점이 매우 길군요

2022-03-28 13:19 UTC, yeonduing commented on FancyMouse/Presentation/Folder/View/FolderViewController.swift
> +    func okWasTapped() {
원래 우리 네이밍에 버튼 안붙였나?

2022-03-28 13:19 UTC, yeonduing commented on FancyMouse/Presentation/Folder/View/FolderViewController.swift
> +        let output = viewModel.transform(input: input)
인풋 아웃풋 방식에 대해 회의때 같이 논의해보면 좋을 것 같아

2022-03-28 13:19 UTC, yeonduing commented on FancyMouse/Presentation/Folder/View/PopUpView/FolderAddEditView/FolderAddEditView.swift
> +                guard let self = self,
self 잡은 이유가 궁금해

2022-03-28 13:19 UTC, yeonduing commented on FancyMouse/Presentation/Folder/ViewModel/FolderViewModel.swift
>      lazy var folderList = BehaviorRelay<[Folder?]>(value: [])
relay를 외부에서 바로 접근 가능하네

2022-03-28 13:19 UTC, yeonduing commented on FancyMouse/Presentation/Folder/ViewModel/FolderViewModel.swift
> +    func update(folderID: String, folderColor: String, folderName: String) {
FolderID 안쓴 이유 궁금해

2022-03-28 13:19 UTC, yeonduing commented on FancyMouse/Presentation/Folder/ViewModel/FolderViewModel.swift
> +            return !$0.0.isEmpty && !$0.1.isEmpty
컴팩트 맵 같은걸로 안되는건가?

2022-03-28 13:19 UTC, yeonduing commented on FancyMouse/Utils/BottomSheet.swift
> +    override func touchesBegan(_ touches: Set<UITouch>, with event: UIEvent?) {
<img width="763" alt="스크린샷 2022-03-28 오후 10 17 25" src="https://user-images.githubusercontent.com/60538517/160406224-e3c0388f-aabf-481c-b1b7-731f777aa5ce.png">

[출처: touchesBegan(_:with:)](https://developer.apple.com/documentation/uikit/uiresponder/1621142-touchesbegan)

override 할 때 super 호출 필요해보여

2022-04-03 12:35 UTC, Hansangjin98 commented on FancyMouse/Domain/UseCases/FolderUseCase.swift
> +        }
반영완료~😁

2022-04-03 12:35 UTC, Hansangjin98 commented on FancyMouse/Domain/UseCases/FolderUseCase.swift
>          }
반영완료~😁

2022-04-03 12:36 UTC, Hansangjin98 commented on FancyMouse/Presentation/Folder/View/FolderViewController.swift
> +        guard let colorName = folder.folderColor?.name else { return }
반영완료~😁

2022-04-03 12:36 UTC, Hansangjin98 commented on FancyMouse/Presentation/Folder/View/FolderViewController.swift
> +       folderAddEditView.viewModel.folderID.accept(folder.folderID)
반영완료~😁

2022-04-03 12:37 UTC, Hansangjin98 commented on FancyMouse/Presentation/Folder/ViewModel/FolderViewModel.swift
>      lazy var folderList = BehaviorRelay<[Folder?]>(value: [])
다음에 올릴 PR에서 반영 예정!!

2022-04-03 12:37 UTC, Hansangjin98 commented on FancyMouse/Utils/BottomSheet.swift
> +    override func touchesBegan(_ touches: Set<UITouch>, with event: UIEvent?) {
반영완료~😁

2022-04-03 12:46 UTC, Hansangjin98 commented on FancyMouse/Presentation/Folder/View/FolderViewController.swift
> +    func moreButtonEditWasTapped(_ folder: Folder) {
반영완료~😁

2022-04-05 13:04 UTC, sudingcream approved these changes

2022-04-05 13:21 UTC, yeonduing commented on FancyMouse/Domain/UseCases/FolderUseCase.swift
> +        return folderArray
```swift
guard folders.count > 1
else { return folders }

return folders
         .compactMap { $0 }
         .sorted { $0.createdAt < $1.createdAt }
```

2022-04-05 13:21 UTC, yeonduing commented on FancyMouse/Domain/UseCases/FolderUseCase.swift
> +    func sortFolders(_ folderArray: [Folder?]) -> [Folder?] {
mutable한건 아니니 sorted로 이름 변경해도 될것 같아
그리고 optional을 받지 말고 nil 대신 `추가하기`를 표현하는 구조체를 만들어 주면 좋을 것 같아

2022-04-05 13:34 UTC, lsh424 reviewed
고생했어 상진~!!!!!

2022-04-05 13:34 UTC, lsh424 commented on FancyMouse/Presentation/Folder/ViewModel/FolderViewModel.swift
> +        var isEnableCreate: Driver<Bool>
네이밍이 조금 더 명확하면 좋을듯!  isEnableCreat000 이런식으로

2022-04-05 14:36 UTC, Hansangjin98 commented on FancyMouse/Domain/UseCases/FolderUseCase.swift
> +        return folderArray
알려줘서 고마워~!!!👍

2022-04-05 14:36 UTC, Hansangjin98 commented on FancyMouse/Presentation/Folder/ViewModel/FolderViewModel.swift
> +        var isEnableCreate: Driver<Bool>
반영완료~!!!

2022-04-10 14:35 UTC, Hansangjin98 commented on FancyMouse/Domain/UseCases/FolderUseCase.swift
> +    func sortFolders(_ folderArray: [Folder?]) -> [Folder?] {
반영 완료~!!!

2022-04-11 04:51 UTC, merged